### PR TITLE
Upgrade to 126.0.6478.182-r1 version

### PR DESCRIPTION
**Pull request by evdokimovs**
Upgrade `libwebrtc` version to 126.0.6478.182-r1.

### CODE REVIEW

**Comment by evdokimovs** [comment]
## FCM

```md
Upgrade to 126.0.6478.182.rc.1 version (#111)
```

**Review by tyranron — CHANGES_REQUESTED** [review]
Discussed

**Comment by evdokimovs** [comment]
I couldn't make the `upgrade-ver.sh` script much simpler and more like our old one, because the logic of revision removing after version upgrade requires old and new versions comparison (and it's the main part of script complication). So I implemented new logic based on the `REVISION` var from the `VERSION` file based on the new script.

**Review by tyranron — APPROVED** [review]
@evdokimovs naahh... just required a little bit more effort.

**Pull request merged**
